apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-pagina-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pagina-prueba
  template:
    metadata:
      labels:
        app: pagina-prueba
    spec:
      containers:
      - name: mi-pagina-uaem-container
        image: pagina_prueba
        ports:
        - containerPort: 80
